version: '3'
services:
  database:
    image: mysql/mysql-server:8.0
    ports:
        - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: 'spring'
        MYSQL_DATABASE: 'plataforma'
        MYSQL_USER: 'springuser'
        MYSQL_PASSWORD: 'spring'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
        - './database:/var/lib/mysql'