spring:
  datasource:
    username: springuser
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/plataforma
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  error:
    include-stacktrace: never


app:
  secret-key: DfoK4@scR^MJ!7A7OhOP9KBd&YOq(s**RUGE$AQ$zckq0L%tHpW1*pnC6Y!2P^9C