spring:
  datasource:
    username: springuser
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/plataforma
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true